### ISSUE TITLE
Viltali's CNC Tap Result Validation

### ISSUE THREAD

**Issue by phazil** [Anonoei/klipper_auto_tap#6]
Setup:
350mm Trident
Vitali's CNC Tap
Revo Nozzles

![Screenshot_3](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/f22bc466-2e44-40a0-8db4-99216d23d8e8)

I've defined tap_version with RC8 which based off of the other issue page should work. Currently using a hand measured probe offset of -0.630 on my older PEI sheet. When running first AUTO_TAP it's giving a value of 1.250
![Screenshot_6](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/8c29cb52-dbdc-4414-8630-0a9e32a484fc)
And when validated when going to G0 Z0.25 the nozzle is definitely higher.

![IMG_6582](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/e58b8fca-e2e8-45ee-8575-d87b6a77d859)

When running Force=1 I end up with the same result
![Screenshot_7](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/f826e4f6-1de7-4eea-9cb3-0107d5615bf1)

**Comment by Anonoei** [comment]
@phazil Hmmmm. I'm not sure of the differences between R8 and Viltali's
Doing the rough math that seems like
Viltali = `travel mean * 25 = 0.625`...
Current math for R8 is `(travel mean * 10) + 1`

**Comment by Anonoei** [comment]
@phazil newest version has new math for Vitalii, it should work better for you now. Let me know if it's still off. Thanks for helping with this and staying active!

**Comment by phazil** [comment]
Here's new results with the new method(s?). Probe offset calibrated to around -0.680 on this textured sheet. Got a value of 1.067.
![Screenshot_1](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/0ff2701a-6e7c-40d6-80c2-cf96db1eae98)
![IMG_6656](https://github.com/Anonoei/klipper_auto_tap/assets/15386418/372af2b1-60b2-49f2-9942-2ac09a0eb16c)

@Anonoei

**Comment by Anonoei** [comment]
Multiple of 21.5 was validated by:
 - eightfinger
 - CWeed14
 - Mezabaru
 
 See eightfinger's initial message about it [here](https://discord.com/channels/460117602945990666/1161905815607840768/1165920891457253476)
